#ifndef _STD_H
#define _STD_H

#define INITIAL_START_LEVEL 10.0

#define INITIAL_BW_IN_SEMITONES 4.0

#define INITIAL_CARR_BW_IN_SEMITONES 4.0
#define INITIAL_MOD_BW_IN_SEMITONES 4.0
#define INITIAL_GAIN 1.0

#define LOWER_ENVELOPE_ATTACK_TEMPERATURE 0.01
#define INITIAL_ENVELOPE_ATTACK_TEMPERATURE 1
#define UPPER_ENVELOPE_ATTACK_TEMPERATURE 100
#define LOWER_ENVELOPE_RELEASE_TEMPERATURE 0.01
#define INITIAL_ENVELOPE_RELEASE_TEMPERATURE 5
#define UPPER_ENVELOPE_RELEASE_TEMPERATURE 100
#define ENVELOPE_TEMPERATURE 10

#define CENTER_PAN_VALUE 0.0
#define INITIAL_PAN   CENTER_PAN_VALUE
#define INITIAL_PAN_OFFSET ((MAX_PAN - MIN_PAN) / 5)

#define UPPER_SMOOTHING_BAND 20
#define SMOOTHING_FACTOR 10
#define PI 3.1415828
#define FFSAMP 44100.0
#define NR_OF_BANDS 31
#define FALSE 0
#define TRUE 1

#define INITIAL_CARRIER_GAIN 1.0
#define MAX_CARRIER_GAIN 3.0
#define INITIAL_MODULATOR_GAIN 1.0
#define MAX_MODULATOR_GAIN 3.0

#define INITIAL_ATTACK_TIME 1 // ms
#define INITIAL_RELEASE_TIME 1 // ms

#define MAX_SHORT 32767

float fl_max(float, float);
float fl_min(float, float);
float fl_abs(float);
#endif
